// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TAddress is the golang structure of table t_address for DAO operations like Where/Data.
type TAddress struct {
	g.Meta       `orm:"table:t_address, do:true"`
	Id           interface{} // 唯一自增ID
	UserId       interface{} // 用户id
	ContactName  interface{} // 联系人
	Phone        interface{} // 手机号
	Path         interface{} // 地址
	Doorplate    interface{} // 门牌号
	Lat          interface{} // 纬度
	Lnt          interface{} // 经度
	IsDefault    interface{} // 是否默认
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
