// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TInviteAttention is the golang structure of table t_invite_attention for DAO operations like Where/Data.
type TInviteAttention struct {
	g.Meta       `orm:"table:t_invite_attention, do:true"`
	Id           interface{} // 唯一自增ID
	UserId       interface{} // 邀请人id
	UserOpenid   interface{} // 邀请人openid
	ShareCode    interface{} // 邀请码（解码后的值，暂时无用）
	Openid       interface{} // 被邀请人openid
	Event        interface{} // 事件（关注subject、扫码scan）
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
