// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurPicExamine is the golang structure of table t_masseur_pic_examine for DAO operations like Where/Data.
type TMasseurPicExamine struct {
	g.Meta       `orm:"table:t_masseur_pic_examine, do:true"`
	Id           interface{} // 唯一自增ID
	MasseurId    interface{} //
	Pic          interface{} // 图片
	PicType      interface{} // 图片类型,profession职业照，life生活照
	Approval     interface{} // 0待审批1审批通过2审批不通过
	ApprovalUser interface{} // 审批人
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
