// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurRecruit is the golang structure of table t_masseur_recruit for DAO operations like Where/Data.
type TMasseurRecruit struct {
	g.Meta       `orm:"table:t_masseur_recruit, do:true"`
	Id           interface{} // 唯一自增ID
	Name         interface{} // 姓名
	Sex          interface{} // 性别1男2女
	Phone        interface{} // 手机号
	Age          interface{} // 年龄
	City         interface{} // 意向城市
	Pic          interface{} // 图片
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
