// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurDescHistory is the golang structure of table t_masseur_desc_history for DAO operations like Where/Data.
type TMasseurDescHistory struct {
	g.Meta       `orm:"table:t_masseur_desc_history, do:true"`
	Id           interface{} // 唯一自增ID
	MasseurId    interface{} //
	Desc         interface{} // 简介
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
