// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TOrder is the golang structure of table t_order for DAO operations like Where/Data.
type TOrder struct {
	g.Meta        `orm:"table:t_order, do:true"`
	Id            interface{} // 唯一自增ID
	OrderId       interface{} // 订单id
	MasseurId     interface{} // 服务id
	UserId        interface{} // 用户id
	ServiceTime   *gtime.Time // 预约服务时间
	UserName      interface{} // 联系人（客户）
	Phone         interface{} // 联系电话（客户）
	VirtualPhone  interface{} // 虚拟电话
	Address       interface{} // 地址
	Lat           interface{} // 用户纬度
	Lnt           interface{} // 用户经度
	TrafficType   interface{} // 交通方式,0出租1公交
	Distance      interface{} // 距离,单位km
	CancelReason  interface{} // 取消原因
	Remark        interface{} // 订单备注
	TotalMoney    interface{} // 订单金额（分）
	CarMoney      interface{} // 出行费
	ServiceMoney  interface{} // 项目总价
	CouponId      interface{} // 使用的优惠券
	CouponMoney   interface{} // 优惠券的金额
	PayType       interface{} // 支付方式0余额支付1汇付宝支付
	PayTime       *gtime.Time // 支付时间
	Status        interface{} // 订单状态
	SignPic       interface{} // 签字确认图片
	TechComment   interface{} // 技师是否评论
	UserComment   interface{} // 用户是否评论
	UserComplaint interface{} // 用户是否投诉
	Enabled       interface{} //
	CreatedTime   *gtime.Time // 创建时间
	ModifiedTime  *gtime.Time // 更新时间
}
