// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TOrderService is the golang structure of table t_order_service for DAO operations like Where/Data.
type TOrderService struct {
	g.Meta       `orm:"table:t_order_service, do:true"`
	Id           interface{} // 唯一自增ID
	OrderId      interface{} // 订单id
	SubOrderId   interface{} // 子工单id(加钟)
	ServiceId    interface{} // 服务id
	ServiceName  interface{} // 服务项目名称
	ServiceDesc  interface{} // 服务项目描述
	ServiceLabel interface{} // 标签（显示在名称旁边）
	ServicePrice interface{} // 价格(分)
	ServicePic   interface{} // 首页缩略图
	ServiceTime  interface{} // 服务时长
	Num          interface{} // 服务数量
	SvType       interface{} // 服务来源，为空表示正常选，up表示项目升级，add表示加钟
	Enabled      interface{} // 是否有效0否1是
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
