// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TPay is the golang structure of table t_pay for DAO operations like Where/Data.
type TPay struct {
	g.Meta       `orm:"table:t_pay, do:true"`
	Id           interface{} // 唯一自增ID
	PreId        interface{} // 预支付id
	BusinessType interface{} // 业务类型,order订单，ord_add加钟，ord_up升级，cz充值
	BusinessId   interface{} // 对应类型的业务id
	PayStatus    interface{} // 支付状态 create创建订单，支付失败fail，支付成功success
	BackTime     *gtime.Time // 回调时间
	BackContent  interface{} // 回调内容
	BackType     interface{} // 回调方式，search主动查询，callback三方回调
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
