// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TService is the golang structure of table t_service for DAO operations like Where/Data.
type TService struct {
	g.Meta       `orm:"table:t_service, do:true"`
	Id           interface{} // 唯一自增ID
	ServiceId    interface{} // 服务id
	Name         interface{} // 服务项目名称
	Desc         interface{} // 服务项目描述
	Label        interface{} // 标签（显示在名称旁边）
	Price        interface{} // 价格(分)
	SPic         interface{} // 首页缩略图
	BPic         interface{} // 详情页大图片
	ServiceTime  interface{} // 服务时长
	Cnt          interface{} // 服务被预定次数
	Content      interface{} // 详情页内容（图片）
	IsShow       interface{} // 是否首页展示
	Enabled      interface{} // 是否有效0否1是
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
