// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserDetails is the golang structure of table t_user_details for DAO operations like Where/Data.
type TUserDetails struct {
	g.Meta       `orm:"table:t_user_details, do:true"`
	Id           interface{} // 唯一自增ID
	UserId       interface{} // 用户openid
	OrderId      interface{} // 订单号
	Status       interface{} // 状态，已完成finish，失败fail
	Money        interface{} // 金额(分)
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
