// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserTopUp is the golang structure of table t_user_top_up for DAO operations like Where/Data.
type TUserTopUp struct {
	g.Meta        `orm:"table:t_user_top_up, do:true"`
	Id            interface{} // 唯一自增ID
	UserId        interface{} // 用户openid
	UpId          interface{} // 充值订单号
	Status        interface{} // 状态，已完成finish，失败fail
	BdMasseurId   interface{} // 绑定的技师ID,自增ID
	BdMasseurName interface{} // 绑定的技师名称
	Give          interface{} // 赠送的金额
	Money         interface{} // 总金额，包含赠送的(分)
	Enabled       interface{} //
	CreatedTime   *gtime.Time // 创建时间
	ModifiedTime  *gtime.Time // 更新时间
}
