// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserRefund is the golang structure of table t_user_refund for DAO operations like Where/Data.
type TUserRefund struct {
	g.Meta       `orm:"table:t_user_refund, do:true"`
	Id           interface{} // 唯一自增ID
	UserId       interface{} // 用户openid
	Money        interface{} // 退款金额(分)
	Reason       interface{} // 退款原因
	Operator     interface{} // 操作人
	OperatorTime *gtime.Time // 操作时间
	Status       interface{} // 退款状态
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
