// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TMasseurLocationDao is the data access object for table t_masseur_location.
type TMasseurLocationDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns TMasseurLocationColumns // columns contains all the column names of Table for convenient usage.
}

// TMasseurLocationColumns defines and stores column names for table t_masseur_location.
type TMasseurLocationColumns struct {
	Id           string // 唯一自增ID
	MasseurId    string //
	Lnt          string // 经度
	Lat          string // 纬度
	Address      string // 地址信息
	Enabled      string //
	CreatedTime  string // 创建时间
	ModifiedTime string // 更新时间
}

// tMasseurLocationColumns holds the columns for table t_masseur_location.
var tMasseurLocationColumns = TMasseurLocationColumns{
	Id:           "id",
	MasseurId:    "masseur_id",
	Lnt:          "lnt",
	Lat:          "lat",
	Address:      "address",
	Enabled:      "enabled",
	CreatedTime:  "created_time",
	ModifiedTime: "modified_time",
}

// NewTMasseurLocationDao creates and returns a new DAO object for table data access.
func NewTMasseurLocationDao() *TMasseurLocationDao {
	return &TMasseurLocationDao{
		group:   "default",
		table:   "t_masseur_location",
		columns: tMasseurLocationColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TMasseurLocationDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TMasseurLocationDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TMasseurLocationDao) Columns() TMasseurLocationColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TMasseurLocationDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TMasseurLocationDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TMasseurLocationDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
