// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TUserCouponDao is the data access object for table t_user_coupon.
type TUserCouponDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns TUserCouponColumns // columns contains all the column names of Table for convenient usage.
}

// TUserCouponColumns defines and stores column names for table t_user_coupon.
type TUserCouponColumns struct {
	Id       string // 唯一自增ID
	UserId   string // 用户id
	CouponId string // 优惠券id
	IsUse    string // 是否被使用0否1是
	Enabled  string // 是否有效0否1是
	STime    string // 开始使用时间
	ETime    string // 结束使用时间
}

// tUserCouponColumns holds the columns for table t_user_coupon.
var tUserCouponColumns = TUserCouponColumns{
	Id:       "id",
	UserId:   "user_id",
	CouponId: "coupon_id",
	IsUse:    "is_use",
	Enabled:  "enabled",
	STime:    "s_time",
	ETime:    "e_time",
}

// NewTUserCouponDao creates and returns a new DAO object for table data access.
func NewTUserCouponDao() *TUserCouponDao {
	return &TUserCouponDao{
		group:   "default",
		table:   "t_user_coupon",
		columns: tUserCouponColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TUserCouponDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TUserCouponDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TUserCouponDao) Columns() TUserCouponColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TUserCouponDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TUserCouponDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TUserCouponDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
