// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TUserRefundDao is the data access object for table t_user_refund.
type TUserRefundDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns TUserRefundColumns // columns contains all the column names of Table for convenient usage.
}

// TUserRefundColumns defines and stores column names for table t_user_refund.
type TUserRefundColumns struct {
	Id           string // 唯一自增ID
	UserId       string // 用户openid
	Money        string // 退款金额(分)
	Reason       string // 退款原因
	Operator     string // 操作人
	OperatorTime string // 操作时间
	Status       string // 退款状态
	Enabled      string //
	CreatedTime  string // 创建时间
	ModifiedTime string // 更新时间
}

// tUserRefundColumns holds the columns for table t_user_refund.
var tUserRefundColumns = TUserRefundColumns{
	Id:           "id",
	UserId:       "user_id",
	Money:        "money",
	Reason:       "reason",
	Operator:     "operator",
	OperatorTime: "operator_time",
	Status:       "status",
	Enabled:      "enabled",
	CreatedTime:  "created_time",
	ModifiedTime: "modified_time",
}

// NewTUserRefundDao creates and returns a new DAO object for table data access.
func NewTUserRefundDao() *TUserRefundDao {
	return &TUserRefundDao{
		group:   "default",
		table:   "t_user_refund",
		columns: tUserRefundColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TUserRefundDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TUserRefundDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TUserRefundDao) Columns() TUserRefundColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TUserRefundDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TUserRefundDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TUserRefundDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
