// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TUserTopUpDao is the data access object for table t_user_top_up.
type TUserTopUpDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns TUserTopUpColumns // columns contains all the column names of Table for convenient usage.
}

// TUserTopUpColumns defines and stores column names for table t_user_top_up.
type TUserTopUpColumns struct {
	Id            string // 唯一自增ID
	UserId        string // 用户openid
	UpId          string // 充值订单号
	Status        string // 状态，已完成finish，失败fail
	BdMasseurId   string // 绑定的技师ID,自增ID
	BdMasseurName string // 绑定的技师名称
	Give          string // 赠送的金额
	Money         string // 总金额，包含赠送的(分)
	Enabled       string //
	CreatedTime   string // 创建时间
	ModifiedTime  string // 更新时间
}

// tUserTopUpColumns holds the columns for table t_user_top_up.
var tUserTopUpColumns = TUserTopUpColumns{
	Id:            "id",
	UserId:        "user_id",
	UpId:          "up_id",
	Status:        "status",
	BdMasseurId:   "bd_masseur_id",
	BdMasseurName: "bd_masseur_name",
	Give:          "give",
	Money:         "money",
	Enabled:       "enabled",
	CreatedTime:   "created_time",
	ModifiedTime:  "modified_time",
}

// NewTUserTopUpDao creates and returns a new DAO object for table data access.
func NewTUserTopUpDao() *TUserTopUpDao {
	return &TUserTopUpDao{
		group:   "default",
		table:   "t_user_top_up",
		columns: tUserTopUpColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TUserTopUpDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TUserTopUpDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TUserTopUpDao) Columns() TUserTopUpColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TUserTopUpDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TUserTopUpDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TUserTopUpDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
