// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TInviteAttention is the golang structure for table t_invite_attention.
type TInviteAttention struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	UserId       string      `json:"userId"       description:"邀请人id"`
	UserOpenid   string      `json:"userOpenid"   description:"邀请人openid"`
	ShareCode    string      `json:"shareCode"    description:"邀请码（解码后的值，暂时无用）"`
	Openid       string      `json:"openid"       description:"被邀请人openid"`
	Event        string      `json:"event"        description:"事件（关注subject、扫码scan）"`
	Enabled      int         `json:"enabled"      description:""`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
