// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurService is the golang structure for table t_masseur_service.
type TMasseurService struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	ServiceId    string      `json:"serviceId"    description:"服务id"`
	MasseurId    string      `json:"masseurId"    description:"技师id"`
	Status       int         `json:"status"       description:"状态 0软删除 1使用"`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
