// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseur is the golang structure for table t_masseur.
type TMasseur struct {
	Id             int         `json:"id"             description:"自增ID"`
	MasseurId      string      `json:"masseurId"      description:"用户唯一Id"`
	Name           string      `json:"name"           description:"真实姓名"`
	Sex            int         `json:"sex"            description:"0未知1男2女"`
	NickName       string      `json:"nickName"       description:"对外昵称"`
	Desc           string      `json:"desc"           description:"描述"`
	Phone          string      `json:"phone"          description:"手机号"`
	Openid         string      `json:"openid"         description:"openid"`
	WxId           string      `json:"wxId"           description:"微信号"`
	Balance        int         `json:"balance"        description:"账户余额（分）"`
	DrawMoney      int         `json:"drawMoney"      description:"可提现金额（分）"`
	Points         int         `json:"points"         description:"积分"`
	Level          int         `json:"level"          description:"等级"`
	Score          float64     `json:"score"          description:"评分"`
	City           int         `json:"city"           description:"城市（地区代码）,默认重庆"`
	AcceptTime     string      `json:"acceptTime"     description:"可预约时间1为可接单 0表示不接单 2表示已预约"`
	SystemStop     int         `json:"systemStop"     description:"是否系统停牌 0否1是"`
	AutoLocation   int         `json:"autoLocation"   description:"自动更新地理位置 0否1是"`
	Lat            float64     `json:"lat"            description:"纬度"`
	Lnt            float64     `json:"lnt"            description:"经度"`
	BusinessAbbrev string      `json:"businessAbbrev" description:"营业执照简称（4个字）"`
	BusinessName   string      `json:"businessName"   description:"营业执照全称"`
	BusinessPic    string      `json:"businessPic"    description:"营业执照图片"`
	IdCard         string      `json:"idCard"         description:"身份证号码"`
	ProfessionPic  string      `json:"professionPic"  description:"职业照"`
	LifePic        string      `json:"lifePic"        description:"生活照"`
	UnionId        string      `json:"unionId"        description:"微信unionId"`
	CreatedTime    *gtime.Time `json:"createdTime"    description:"创建时间"`
	ModifiedTime   *gtime.Time `json:"modifiedTime"   description:"更新时间"`
}
