// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurLocation is the golang structure for table t_masseur_location.
type TMasseurLocation struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	MasseurId    string      `json:"masseurId"    description:""`
	Lnt          float64     `json:"lnt"          description:"经度"`
	Lat          float64     `json:"lat"          description:"纬度"`
	Address      string      `json:"address"      description:"地址信息"`
	Enabled      int         `json:"enabled"      description:""`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
