// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TOrderService is the golang structure for table t_order_service.
type TOrderService struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	OrderId      string      `json:"orderId"      description:"订单id"`
	SubOrderId   string      `json:"subOrderId"   description:"子工单id(加钟)"`
	ServiceId    string      `json:"serviceId"    description:"服务id"`
	ServiceName  string      `json:"serviceName"  description:"服务项目名称"`
	ServiceDesc  string      `json:"serviceDesc"  description:"服务项目描述"`
	ServiceLabel string      `json:"serviceLabel" description:"标签（显示在名称旁边）"`
	ServicePrice int         `json:"servicePrice" description:"价格(分)"`
	ServicePic   string      `json:"servicePic"   description:"首页缩略图"`
	ServiceTime  int         `json:"serviceTime"  description:"服务时长"`
	Num          int         `json:"num"          description:"服务数量"`
	SvType       string      `json:"svType"       description:"服务来源，为空表示正常选，up表示项目升级，add表示加钟"`
	Enabled      int         `json:"enabled"      description:"是否有效0否1是"`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
