// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TService is the golang structure for table t_service.
type TService struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	ServiceId    string      `json:"serviceId"    description:"服务id"`
	Name         string      `json:"name"         description:"服务项目名称"`
	Desc         string      `json:"desc"         description:"服务项目描述"`
	Label        string      `json:"label"        description:"标签（显示在名称旁边）"`
	Price        int         `json:"price"        description:"价格(分)"`
	SPic         string      `json:"sPic"         description:"首页缩略图"`
	BPic         string      `json:"bPic"         description:"详情页大图片"`
	ServiceTime  int         `json:"serviceTime"  description:"服务时长"`
	Cnt          int         `json:"cnt"          description:"服务被预定次数"`
	Content      string      `json:"content"      description:"详情页内容（图片）"`
	IsShow       int         `json:"isShow"       description:"是否首页展示"`
	Enabled      int         `json:"enabled"      description:"是否有效0否1是"`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
