// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserCoupon is the golang structure for table t_user_coupon.
type TUserCoupon struct {
	Id       int         `json:"id"       description:"唯一自增ID"`
	UserId   string      `json:"userId"   description:"用户id"`
	CouponId string      `json:"couponId" description:"优惠券id"`
	IsUse    int         `json:"isUse"    description:"是否被使用0否1是"`
	Enabled  int         `json:"enabled"  description:"是否有效0否1是"`
	STime    *gtime.Time `json:"sTime"    description:"开始使用时间"`
	ETime    *gtime.Time `json:"eTime"    description:"结束使用时间"`
}
