// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTAddressDao is internal type for wrapping internal DAO implements.
type internalTAddressDao = *internal.TAddressDao

// tAddressDao is the data access object for table t_address.
// You can define custom methods on it to extend its functionality as you wish.
type tAddressDao struct {
	internalTAddressDao
}

var (
	// TAddress is globally public accessible object for table t_address operations.
	TAddress = tAddressDao{
		internal.NewTAddressDao(),
	}
)

// Fill with you ideas below.
