// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTCouponDao is internal type for wrapping internal DAO implements.
type internalTCouponDao = *internal.TCouponDao

// tCouponDao is the data access object for table t_coupon.
// You can define custom methods on it to extend its functionality as you wish.
type tCouponDao struct {
	internalTCouponDao
}

var (
	// TCoupon is globally public accessible object for table t_coupon operations.
	TCoupon = tCouponDao{
		internal.NewTCouponDao(),
	}
)

// Fill with you ideas below.
