// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTMasseurServiceDao is internal type for wrapping internal DAO implements.
type internalTMasseurServiceDao = *internal.TMasseurServiceDao

// tMasseurServiceDao is the data access object for table t_masseur_service.
// You can define custom methods on it to extend its functionality as you wish.
type tMasseurServiceDao struct {
	internalTMasseurServiceDao
}

var (
	// TMasseurService is globally public accessible object for table t_masseur_service operations.
	TMasseurService = tMasseurServiceDao{
		internal.NewTMasseurServiceDao(),
	}
)

// Fill with you ideas below.
