// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTOpinionFeedbackDao is internal type for wrapping internal DAO implements.
type internalTOpinionFeedbackDao = *internal.TOpinionFeedbackDao

// tOpinionFeedbackDao is the data access object for table t_opinion_feedback.
// You can define custom methods on it to extend its functionality as you wish.
type tOpinionFeedbackDao struct {
	internalTOpinionFeedbackDao
}

var (
	// TOpinionFeedback is globally public accessible object for table t_opinion_feedback operations.
	TOpinionFeedback = tOpinionFeedbackDao{
		internal.NewTOpinionFeedbackDao(),
	}
)

// Fill with you ideas below.
