// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTOrderServiceDao is internal type for wrapping internal DAO implements.
type internalTOrderServiceDao = *internal.TOrderServiceDao

// tOrderServiceDao is the data access object for table t_order_service.
// You can define custom methods on it to extend its functionality as you wish.
type tOrderServiceDao struct {
	internalTOrderServiceDao
}

var (
	// TOrderService is globally public accessible object for table t_order_service operations.
	TOrderService = tOrderServiceDao{
		internal.NewTOrderServiceDao(),
	}
)

// Fill with you ideas below.
