// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTPayDao is internal type for wrapping internal DAO implements.
type internalTPayDao = *internal.TPayDao

// tPayDao is the data access object for table t_pay.
// You can define custom methods on it to extend its functionality as you wish.
type tPayDao struct {
	internalTPayDao
}

var (
	// TPay is globally public accessible object for table t_pay operations.
	TPay = tPayDao{
		internal.NewTPayDao(),
	}
)

// Fill with you ideas below.
