// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTUserTopUpDao is internal type for wrapping internal DAO implements.
type internalTUserTopUpDao = *internal.TUserTopUpDao

// tUserTopUpDao is the data access object for table t_user_top_up.
// You can define custom methods on it to extend its functionality as you wish.
type tUserTopUpDao struct {
	internalTUserTopUpDao
}

var (
	// TUserTopUp is globally public accessible object for table t_user_top_up operations.
	TUserTopUp = tUserTopUpDao{
		internal.NewTUserTopUpDao(),
	}
)

// Fill with you ideas below.
