// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/skdj/dao/internal"
)

// internalTUserCouponDao is internal type for wrapping internal DAO implements.
type internalTUserCouponDao = *internal.TUserCouponDao

// tUserCouponDao is the data access object for table t_user_coupon.
// You can define custom methods on it to extend its functionality as you wish.
type tUserCouponDao struct {
	internalTUserCouponDao
}

var (
	// TUserCoupon is globally public accessible object for table t_user_coupon operations.
	TUserCoupon = tUserCouponDao{
		internal.NewTUserCouponDao(),
	}
)

// Fill with you ideas below.
