// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTCollectDao is internal type for wrapping internal DAO implements.
type internalTCollectDao = *internal.TCollectDao

// tCollectDao is the data access object for table t_collect.
// You can define custom methods on it to extend its functionality as you wish.
type tCollectDao struct {
	internalTCollectDao
}

var (
	// TCollect is globally public accessible object for table t_collect operations.
	TCollect = tCollectDao{
		internal.NewTCollectDao(),
	}
)

// Fill with you ideas below.
