// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTMasseurRecruitDao is internal type for wrapping internal DAO implements.
type internalTMasseurRecruitDao = *internal.TMasseurRecruitDao

// tMasseurRecruitDao is the data access object for table t_masseur_recruit.
// You can define custom methods on it to extend its functionality as you wish.
type tMasseurRecruitDao struct {
	internalTMasseurRecruitDao
}

var (
	// TMasseurRecruit is globally public accessible object for table t_masseur_recruit operations.
	TMasseurRecruit = tMasseurRecruitDao{
		internal.NewTMasseurRecruitDao(),
	}
)

// Fill with you ideas below.
