// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTMasseurPicExamineDao is internal type for wrapping internal DAO implements.
type internalTMasseurPicExamineDao = *internal.TMasseurPicExamineDao

// tMasseurPicExamineDao is the data access object for table t_masseur_pic_examine.
// You can define custom methods on it to extend its functionality as you wish.
type tMasseurPicExamineDao struct {
	internalTMasseurPicExamineDao
}

var (
	// TMasseurPicExamine is globally public accessible object for table t_masseur_pic_examine operations.
	TMasseurPicExamine = tMasseurPicExamineDao{
		internal.NewTMasseurPicExamineDao(),
	}
)

// Fill with you ideas below.
