// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTMasseurDao is internal type for wrapping internal DAO implements.
type internalTMasseurDao = *internal.TMasseurDao

// tMasseurDao is the data access object for table t_masseur.
// You can define custom methods on it to extend its functionality as you wish.
type tMasseurDao struct {
	internalTMasseurDao
}

var (
	// TMasseur is globally public accessible object for table t_masseur operations.
	TMasseur = tMasseurDao{
		internal.NewTMasseurDao(),
	}
)

// Fill with you ideas below.
