// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTOrderDao is internal type for wrapping internal DAO implements.
type internalTOrderDao = *internal.TOrderDao

// tOrderDao is the data access object for table t_order.
// You can define custom methods on it to extend its functionality as you wish.
type tOrderDao struct {
	internalTOrderDao
}

var (
	// TOrder is globally public accessible object for table t_order operations.
	TOrder = tOrderDao{
		internal.NewTOrderDao(),
	}
)

// Fill with you ideas below.
