// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTOrderBellDao is internal type for wrapping internal DAO implements.
type internalTOrderBellDao = *internal.TOrderBellDao

// tOrderBellDao is the data access object for table t_order_bell.
// You can define custom methods on it to extend its functionality as you wish.
type tOrderBellDao struct {
	internalTOrderBellDao
}

var (
	// TOrderBell is globally public accessible object for table t_order_bell operations.
	TOrderBell = tOrderBellDao{
		internal.NewTOrderBellDao(),
	}
)

// Fill with you ideas below.
