// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTOrderProcessDao is internal type for wrapping internal DAO implements.
type internalTOrderProcessDao = *internal.TOrderProcessDao

// tOrderProcessDao is the data access object for table t_order_process.
// You can define custom methods on it to extend its functionality as you wish.
type tOrderProcessDao struct {
	internalTOrderProcessDao
}

var (
	// TOrderProcess is globally public accessible object for table t_order_process operations.
	TOrderProcess = tOrderProcessDao{
		internal.NewTOrderProcessDao(),
	}
)

// Fill with you ideas below.
