// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTServiceDao is internal type for wrapping internal DAO implements.
type internalTServiceDao = *internal.TServiceDao

// tServiceDao is the data access object for table t_service.
// You can define custom methods on it to extend its functionality as you wish.
type tServiceDao struct {
	internalTServiceDao
}

var (
	// TService is globally public accessible object for table t_service operations.
	TService = tServiceDao{
		internal.NewTServiceDao(),
	}
)

// Fill with you ideas below.
