// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/tiger1103/gfast/v3/internal/app/system/dao/internal"
)

// internalTUserCommentDao is internal type for wrapping internal DAO implements.
type internalTUserCommentDao = *internal.TUserCommentDao

// tUserCommentDao is the data access object for table t_user_comment.
// You can define custom methods on it to extend its functionality as you wish.
type tUserCommentDao struct {
	internalTUserCommentDao
}

var (
	// TUserComment is globally public accessible object for table t_user_comment operations.
	TUserComment = tUserCommentDao{
		internal.NewTUserCommentDao(),
	}
)

// Fill with you ideas below.
