// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TMasseurContactDao is the data access object for table t_masseur_contact.
type TMasseurContactDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns TMasseurContactColumns // columns contains all the column names of Table for convenient usage.
}

// TMasseurContactColumns defines and stores column names for table t_masseur_contact.
type TMasseurContactColumns struct {
	Id           string // 唯一自增ID
	MasseurId    string //
	Name         string // 姓名
	Phone        string // 手机号
	Enabled      string //
	CreatedTime  string // 创建时间
	ModifiedTime string // 更新时间
}

// tMasseurContactColumns holds the columns for table t_masseur_contact.
var tMasseurContactColumns = TMasseurContactColumns{
	Id:           "id",
	MasseurId:    "masseur_id",
	Name:         "name",
	Phone:        "phone",
	Enabled:      "enabled",
	CreatedTime:  "created_time",
	ModifiedTime: "modified_time",
}

// NewTMasseurContactDao creates and returns a new DAO object for table data access.
func NewTMasseurContactDao() *TMasseurContactDao {
	return &TMasseurContactDao{
		group:   "default",
		table:   "t_masseur_contact",
		columns: tMasseurContactColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TMasseurContactDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TMasseurContactDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TMasseurContactDao) Columns() TMasseurContactColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TMasseurContactDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TMasseurContactDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TMasseurContactDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
