// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TOrderServiceDao is the data access object for table t_order_service.
type TOrderServiceDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns TOrderServiceColumns // columns contains all the column names of Table for convenient usage.
}

// TOrderServiceColumns defines and stores column names for table t_order_service.
type TOrderServiceColumns struct {
	Id           string // 唯一自增ID
	OrderId      string // 订单id
	SubOrderId   string // 子工单id(加钟)
	ServiceId    string // 服务id
	ServiceName  string // 服务项目名称
	ServiceDesc  string // 服务项目描述
	ServiceLabel string // 标签（显示在名称旁边）
	ServicePrice string // 价格(分)
	ServicePic   string // 首页缩略图
	ServiceTime  string // 服务时长
	Num          string // 服务数量
	SvType       string // 服务来源，为空表示正常选，up表示项目升级，add表示加钟
	Enabled      string // 是否有效0否1是
	CreatedTime  string // 创建时间
	ModifiedTime string // 更新时间
}

// tOrderServiceColumns holds the columns for table t_order_service.
var tOrderServiceColumns = TOrderServiceColumns{
	Id:           "id",
	OrderId:      "order_id",
	SubOrderId:   "sub_order_id",
	ServiceId:    "service_id",
	ServiceName:  "service_name",
	ServiceDesc:  "service_desc",
	ServiceLabel: "service_label",
	ServicePrice: "service_price",
	ServicePic:   "service_pic",
	ServiceTime:  "service_time",
	Num:          "num",
	SvType:       "sv_type",
	Enabled:      "enabled",
	CreatedTime:  "created_time",
	ModifiedTime: "modified_time",
}

// NewTOrderServiceDao creates and returns a new DAO object for table data access.
func NewTOrderServiceDao() *TOrderServiceDao {
	return &TOrderServiceDao{
		group:   "default",
		table:   "t_order_service",
		columns: tOrderServiceColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TOrderServiceDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TOrderServiceDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TOrderServiceDao) Columns() TOrderServiceColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TOrderServiceDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TOrderServiceDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TOrderServiceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
