// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TAddress is the golang structure for table t_address.
type TAddress struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	UserId       string      `json:"userId"       description:"用户id"`
	ContactName  string      `json:"contactName"  description:"联系人"`
	Phone        string      `json:"phone"        description:"手机号"`
	Path         string      `json:"path"         description:"地址"`
	Doorplate    string      `json:"doorplate"    description:"门牌号"`
	Lat          float64     `json:"lat"          description:"纬度"`
	Lnt          float64     `json:"lnt"          description:"经度"`
	IsDefault    int         `json:"isDefault"    description:"是否默认"`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
