// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurContact is the golang structure for table t_masseur_contact.
type TMasseurContact struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	MasseurId    string      `json:"masseurId"    description:""`
	Name         string      `json:"name"         description:"姓名"`
	Phone        string      `json:"phone"        description:"手机号"`
	Enabled      int         `json:"enabled"      description:""`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
