// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurRecruit is the golang structure for table t_masseur_recruit.
type TMasseurRecruit struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	Name         string      `json:"name"         description:"姓名"`
	Sex          int         `json:"sex"          description:"性别1男2女"`
	Phone        string      `json:"phone"        description:"手机号"`
	Age          int         `json:"age"          description:"年龄"`
	City         string      `json:"city"         description:"意向城市"`
	Pic          string      `json:"pic"          description:"图片"`
	Enabled      int         `json:"enabled"      description:""`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
