// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurDescHistory is the golang structure for table t_masseur_desc_history.
type TMasseurDescHistory struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	MasseurId    string      `json:"masseurId"    description:""`
	Desc         string      `json:"desc"         description:"简介"`
	Enabled      int         `json:"enabled"      description:""`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
