// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TOrderComplaint is the golang structure for table t_order_complaint.
type TOrderComplaint struct {
	Id             int         `json:"id"             description:"唯一自增ID"`
	OrderId        string      `json:"orderId"        description:"订单id"`
	MasseurId      string      `json:"masseurId"      description:"服务人id"`
	UserId         string      `json:"userId"         description:"用户id"`
	MasseurName    string      `json:"masseurName"    description:"技师名称"`
	ComplaintLabel string      `json:"complaintLabel" description:"投诉类型"`
	Content        string      `json:"content"        description:"投诉内容"`
	Pic            string      `json:"pic"            description:"上传凭证"`
	Phone          string      `json:"phone"          description:"联系方式"`
	Status         string      `json:"status"         description:"状态"`
	CreatedTime    *gtime.Time `json:"createdTime"    description:"创建时间"`
	ModifiedTime   *gtime.Time `json:"modifiedTime"   description:"更新时间"`
}
