// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TOrder is the golang structure for table t_order.
type TOrder struct {
	Id            int         `json:"id"            description:"唯一自增ID"`
	OrderId       string      `json:"orderId"       description:"订单id"`
	MasseurId     string      `json:"masseurId"     description:"服务id"`
	UserId        string      `json:"userId"        description:"用户id"`
	ServiceTime   *gtime.Time `json:"serviceTime"   description:"预约服务时间"`
	UserName      string      `json:"userName"      description:"联系人（客户）"`
	Phone         string      `json:"phone"         description:"联系电话（客户）"`
	VirtualPhone  string      `json:"virtualPhone"  description:"虚拟电话"`
	Address       string      `json:"address"       description:"地址"`
	Lat           float64     `json:"lat"           description:"用户纬度"`
	Lnt           float64     `json:"lnt"           description:"用户经度"`
	TrafficType   int         `json:"trafficType"   description:"交通方式,0出租1公交"`
	Distance      string      `json:"distance"      description:"距离,单位km"`
	CancelReason  string      `json:"cancelReason"  description:"取消原因"`
	Remark        string      `json:"remark"        description:"订单备注"`
	TotalMoney    int         `json:"totalMoney"    description:"订单金额（分）"`
	CarMoney      int         `json:"carMoney"      description:"出行费"`
	ServiceMoney  int         `json:"serviceMoney"  description:"项目总价"`
	CouponId      string      `json:"couponId"      description:"使用的优惠券"`
	CouponMoney   int         `json:"couponMoney"   description:"优惠券的金额"`
	PayType       int         `json:"payType"       description:"支付方式0余额支付1汇付宝支付"`
	PayTime       *gtime.Time `json:"payTime"       description:"支付时间"`
	Status        string      `json:"status"        description:"订单状态"`
	SignPic       string      `json:"signPic"       description:"签字确认图片"`
	TechComment   int         `json:"techComment"   description:"技师是否评论"`
	UserComment   int         `json:"userComment"   description:"用户是否评论"`
	UserComplaint int         `json:"userComplaint" description:"用户是否投诉"`
	Enabled       int         `json:"enabled"       description:""`
	CreatedTime   *gtime.Time `json:"createdTime"   description:"创建时间"`
	ModifiedTime  *gtime.Time `json:"modifiedTime"  description:"更新时间"`
}
