// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserComment is the golang structure for table t_user_comment.
type TUserComment struct {
	Id           int         `json:"id"           description:"唯一自增ID"`
	UserId       string      `json:"userId"       description:"用户id"`
	MasseurId    string      `json:"masseurId"    description:"技师id"`
	OrderId      string      `json:"orderId"      description:"订单id"`
	Score        int         `json:"score"        description:"星级1-5星"`
	Label        string      `json:"label"        description:"标签"`
	Content      string      `json:"content"      description:"评论内容"`
	IsAppeal     int         `json:"isAppeal"     description:"是否申诉0否1是"`
	Enabled      int         `json:"enabled"      description:"是否有效"`
	CreatedTime  *gtime.Time `json:"createdTime"  description:"创建时间"`
	ModifiedTime *gtime.Time `json:"modifiedTime" description:"更新时间"`
}
