// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// TCoupon is the golang structure of table t_coupon for DAO operations like Where/Data.
type TCoupon struct {
	g.Meta        `orm:"table:t_coupon, do:true"`
	Id            interface{} // 唯一自增ID
	CouponId      interface{} // 优惠券id
	FullMoney     interface{} // 满多少可以使用
	SubtractMoney interface{} // 减多少钱
	Scene         interface{} // 应用场景，注册时register,rg_invite邀请注册时,first_xd首次下单
	Enabled       interface{} // 是否有效 0无效
}
