// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TCollect is the golang structure of table t_collect for DAO operations like Where/Data.
type TCollect struct {
	g.Meta      `orm:"table:t_collect, do:true"`
	Id          interface{} // 唯一自增ID
	UserId      interface{} // 用户id
	MasseurId   interface{} // 技师id
	CreatedTime *gtime.Time // 创建时间
}
