// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurLocation is the golang structure of table t_masseur_location for DAO operations like Where/Data.
type TMasseurLocation struct {
	g.Meta       `orm:"table:t_masseur_location, do:true"`
	Id           interface{} // 唯一自增ID
	MasseurId    interface{} //
	Lnt          interface{} // 经度
	Lat          interface{} // 纬度
	Address      interface{} // 地址信息
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
