// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseur is the golang structure of table t_masseur for DAO operations like Where/Data.
type TMasseur struct {
	g.Meta         `orm:"table:t_masseur, do:true"`
	Id             interface{} // 自增ID
	MasseurId      interface{} // 用户唯一Id
	Name           interface{} // 真实姓名
	Sex            interface{} // 0未知1男2女
	NickName       interface{} // 对外昵称
	Desc           interface{} // 描述
	Phone          interface{} // 手机号
	Openid         interface{} // openid
	WxId           interface{} // 微信号
	Balance        interface{} // 账户余额（分）
	DrawMoney      interface{} // 可提现金额（分）
	Points         interface{} // 积分
	Level          interface{} // 等级
	Score          interface{} // 评分
	City           interface{} // 城市（地区代码）,默认重庆
	AcceptTime     interface{} // 可预约时间1为可接单 0表示不接单 2表示已预约
	SystemStop     interface{} // 是否系统停牌 0否1是
	AutoLocation   interface{} // 自动更新地理位置 0否1是
	Lat            interface{} // 纬度
	Lnt            interface{} // 经度
	BusinessAbbrev interface{} // 营业执照简称（4个字）
	BusinessName   interface{} // 营业执照全称
	BusinessPic    interface{} // 营业执照图片
	IdCard         interface{} // 身份证号码
	ProfessionPic  interface{} // 职业照
	LifePic        interface{} // 生活照
	UnionId        interface{} // 微信unionId
	CreatedTime    *gtime.Time // 创建时间
	ModifiedTime   *gtime.Time // 更新时间
}
