// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TMasseurBank is the golang structure of table t_masseur_bank for DAO operations like Where/Data.
type TMasseurBank struct {
	g.Meta       `orm:"table:t_masseur_bank, do:true"`
	Id           interface{} // 唯一自增ID
	MasseurId    interface{} //
	CardId       interface{} // 银行卡号
	CardName     interface{} // 持卡人姓名
	BankName     interface{} // 所属银行
	SubBankName  interface{} // 分行
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
