// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TOpinionFeedback is the golang structure of table t_opinion_feedback for DAO operations like Where/Data.
type TOpinionFeedback struct {
	g.Meta       `orm:"table:t_opinion_feedback, do:true"`
	Id           interface{} // 唯一自增ID
	UserId       interface{} // 用户openid
	Content      interface{} // 反馈内容
	Pic          interface{} // 图片
	Phone        interface{} // 手机号
	Enabled      interface{} //
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
