// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserCoupon is the golang structure of table t_user_coupon for DAO operations like Where/Data.
type TUserCoupon struct {
	g.Meta   `orm:"table:t_user_coupon, do:true"`
	Id       interface{} // 唯一自增ID
	UserId   interface{} // 用户id
	CouponId interface{} // 优惠券id
	IsUse    interface{} // 是否被使用0否1是
	Enabled  interface{} // 是否有效0否1是
	STime    *gtime.Time // 开始使用时间
	ETime    *gtime.Time // 结束使用时间
}
