// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TUserComment is the golang structure of table t_user_comment for DAO operations like Where/Data.
type TUserComment struct {
	g.Meta       `orm:"table:t_user_comment, do:true"`
	Id           interface{} // 唯一自增ID
	UserId       interface{} // 用户id
	MasseurId    interface{} // 技师id
	OrderId      interface{} // 订单id
	Score        interface{} // 星级1-5星
	Label        interface{} // 标签
	Content      interface{} // 评论内容
	IsAppeal     interface{} // 是否申诉0否1是
	Enabled      interface{} // 是否有效
	CreatedTime  *gtime.Time // 创建时间
	ModifiedTime *gtime.Time // 更新时间
}
